language: go

os:
  - linux

compiler:
  - gcc
  - clang

go_import_path: github.com/wamuir/gohex

go:
  - 1.14.x
  - 1.15.x
  - tip

script:
       - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
       - bash <(curl -s https://codecov.io/bash)
